name = "SymbolicThreeBodyDecays"
uuid = "438db224-8de1-4261-8626-6714e9fac126"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
ThreeBodyDecay = "e6563dab-9ca1-5843-bde3-2ccf38d63843"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
